# Use Python 3.11 slim image
FROM python:3.11-slim

WORKDIR /app

# Copy and install dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
COPY . .

# Set environment port for Cloud Run
ENV PORT 8080

# Start the API
CMD ["python", "main.py"]
